name: 'Comment on PR (javascript action)'
description: 'Adds a comment on PR'
inputs:
  file:
    description: 'Filepath of the comment'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'
